async function asyncFun() {
  try {
    const result = await promise;
  } catch (error) {}
}
